# Generated by Django 5.0.3 on 2024-03-16 05:01

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_post_delete_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("photo", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "image_text",
                        wagtail.blocks.StructBlock(
                            [
                                ("reverse", wagtail.blocks.BooleanBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ]
                        ),
                    ),
                    ("h1", wagtail.blocks.CharBlock()),
                    ("h2", wagtail.blocks.CharBlock()),
                    ("h3", wagtail.blocks.CharBlock()),
                    ("h4", wagtail.blocks.CharBlock()),
                    ("h5", wagtail.blocks.CharBlock()),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("quote_by", wagtail.blocks.CharBlock()),
                                ("text", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    ("link", wagtail.blocks.URLBlock()),
                    (
                        "list",
                        wagtail.blocks.StructBlock(
                            [("ordered", wagtail.blocks.BooleanBlock())]
                        ),
                    ),
                    ("email", wagtail.blocks.EmailBlock()),
                    ("integer_number", wagtail.blocks.IntegerBlock()),
                    ("float_number", wagtail.blocks.FloatBlock()),
                    ("decimal_number", wagtail.blocks.DecimalBlock()),
                    ("date", wagtail.blocks.DateBlock()),
                    ("time", wagtail.blocks.TimeBlock()),
                    ("date_with_time", wagtail.blocks.DateTimeBlock()),
                    ("text", wagtail.blocks.TextBlock()),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("quote_set", wagtail.blocks.BlockQuoteBlock()),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
