# Generated by Django 5.0.3 on 2024-03-16 05:04

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_post_body_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("photo", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "image_text",
                        wagtail.blocks.StructBlock(
                            [
                                ("reverse", wagtail.blocks.BooleanBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ]
                        ),
                    ),
                    ("h1", wagtail.blocks.CharBlock()),
                    ("h2", wagtail.blocks.CharBlock()),
                    ("h3", wagtail.blocks.CharBlock()),
                    ("h4", wagtail.blocks.CharBlock()),
                    ("h5", wagtail.blocks.CharBlock()),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("quote_by", wagtail.blocks.CharBlock()),
                                ("text", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                    ("link", wagtail.blocks.URLBlock()),
                    (
                        "list",
                        wagtail.blocks.StructBlock(
                            [("ordered", wagtail.blocks.BooleanBlock())]
                        ),
                    ),
                    ("email", wagtail.blocks.EmailBlock()),
                    ("integer_number", wagtail.blocks.IntegerBlock()),
                    ("float_number", wagtail.blocks.FloatBlock()),
                    ("decimal_number", wagtail.blocks.DecimalBlock()),
                    ("date", wagtail.blocks.DateBlock()),
                    ("time", wagtail.blocks.TimeBlock()),
                    ("date_with_time", wagtail.blocks.DateTimeBlock()),
                    ("text", wagtail.blocks.TextBlock()),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("quote_set", wagtail.blocks.BlockQuoteBlock()),
                    ("document", wagtail.documents.blocks.DocumentChooserBlock()),
                    ("embed", wagtail.embeds.blocks.EmbedBlock()),
                ]
            ),
        ),
    ]
